### ISSUE TITLE
Timeline for Code Release

### ISSUE THREAD

**Issue by S1M0N38** [shenghh2015/llm-judge-eval#1]
Hi,

Thank you for the paper and for open-sourcing this work.

In the introduction, you mention that one of your contributions is the development of "a framework to evaluate, compare, and visualize the alignment and reliability of LLM judges, with a general and flexible design [...]".

I was wondering if there is any timeline for when the code for this framework will be released (even an early alpha release)? It would be great to know if there has been any progress on that front.

Thanks again!

**Comment by wll199566** [comment]
Hi, 

Thank you so much for your interest in our work! 

We just uploaded our code into the repository. Please feel free to try and test it. 

If there are any questions, please let us know :) 

Thank you!
